// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDATYt4Lp3e3IOsHZ62TBsL1aMoZVRIVMc',
    appId: '1:843199646652:web:538f8c4f12ee457a78b9b9',
    messagingSenderId: '843199646652',
    projectId: 'voting-system-ifsp',
    authDomain: 'voting-system-ifsp.firebaseapp.com',
    storageBucket: 'voting-system-ifsp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMeSPXUi150d5y3OkMFU-yTRA-Qq9bSH4',
    appId: '1:843199646652:android:e131caf58533f6b678b9b9',
    messagingSenderId: '843199646652',
    projectId: 'voting-system-ifsp',
    storageBucket: 'voting-system-ifsp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJTp6slpVIpCVBDYsFWpoHmRTaPAUiW0M',
    appId: '1:843199646652:ios:1c268c2bd7e8f42a78b9b9',
    messagingSenderId: '843199646652',
    projectId: 'voting-system-ifsp',
    storageBucket: 'voting-system-ifsp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJTp6slpVIpCVBDYsFWpoHmRTaPAUiW0M',
    appId: '1:843199646652:ios:1c268c2bd7e8f42a78b9b9',
    messagingSenderId: '843199646652',
    projectId: 'voting-system-ifsp',
    storageBucket: 'voting-system-ifsp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDATYt4Lp3e3IOsHZ62TBsL1aMoZVRIVMc',
    appId: '1:843199646652:web:3413f3e7bc514b8d78b9b9',
    messagingSenderId: '843199646652',
    projectId: 'voting-system-ifsp',
    authDomain: 'voting-system-ifsp.firebaseapp.com',
    storageBucket: 'voting-system-ifsp.firebasestorage.app',
  );
}
